// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.15.8
// source: grpc_Cpu/protobuf/cpu_temp.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Units struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Temp []*Temperature `protobuf:"bytes,1,rep,name=Temp,proto3" json:"Temp,omitempty"`
}

func (x *Units) Reset() {
	*x = Units{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_Cpu_protobuf_cpu_temp_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Units) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Units) ProtoMessage() {}

func (x *Units) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_Cpu_protobuf_cpu_temp_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Units.ProtoReflect.Descriptor instead.
func (*Units) Descriptor() ([]byte, []int) {
	return file_grpc_Cpu_protobuf_cpu_temp_proto_rawDescGZIP(), []int{0}
}

func (x *Units) GetTemp() []*Temperature {
	if x != nil {
		return x.Temp
	}
	return nil
}

type Temperature struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Unit      string  `protobuf:"bytes,1,opt,name=Unit,proto3" json:"Unit,omitempty"`
	Current   float64 `protobuf:"fixed64,2,opt,name=Current,proto3" json:"Current,omitempty"`
	High      float64 `protobuf:"fixed64,3,opt,name=High,proto3" json:"High,omitempty"`
	Critical  float64 `protobuf:"fixed64,4,opt,name=Critical,proto3" json:"Critical,omitempty"`
	TimeStamp int64   `protobuf:"varint,5,opt,name=TimeStamp,proto3" json:"TimeStamp,omitempty"`
}

func (x *Temperature) Reset() {
	*x = Temperature{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_Cpu_protobuf_cpu_temp_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Temperature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Temperature) ProtoMessage() {}

func (x *Temperature) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_Cpu_protobuf_cpu_temp_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Temperature.ProtoReflect.Descriptor instead.
func (*Temperature) Descriptor() ([]byte, []int) {
	return file_grpc_Cpu_protobuf_cpu_temp_proto_rawDescGZIP(), []int{1}
}

func (x *Temperature) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *Temperature) GetCurrent() float64 {
	if x != nil {
		return x.Current
	}
	return 0
}

func (x *Temperature) GetHigh() float64 {
	if x != nil {
		return x.High
	}
	return 0
}

func (x *Temperature) GetCritical() float64 {
	if x != nil {
		return x.Critical
	}
	return 0
}

func (x *Temperature) GetTimeStamp() int64 {
	if x != nil {
		return x.TimeStamp
	}
	return 0
}

// A generic empty message that you can re-use to avoid defining duplicated
// empty messages in your APIs. A typical example is to use it as the request
// or the response type of an API method. For instance:
//
//     service Foo {
//       rpc Bar(google.protobuf.Empty) returns (google.protobuf.Empty);
//     }
//
// The JSON representation for `Empty` is empty JSON object `{}`.
type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_Cpu_protobuf_cpu_temp_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_Cpu_protobuf_cpu_temp_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_grpc_Cpu_protobuf_cpu_temp_proto_rawDescGZIP(), []int{2}
}

var File_grpc_Cpu_protobuf_cpu_temp_proto protoreflect.FileDescriptor

var file_grpc_Cpu_protobuf_cpu_temp_proto_rawDesc = []byte{
	0x0a, 0x20, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x43, 0x70, 0x75, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x63, 0x70, 0x75, 0x5f, 0x74, 0x65, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x07, 0x63, 0x70, 0x75, 0x74, 0x65, 0x6d, 0x70, 0x22, 0x31, 0x0a, 0x05, 0x55,
	0x6e, 0x69, 0x74, 0x73, 0x12, 0x28, 0x0a, 0x04, 0x54, 0x65, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x63, 0x70, 0x75, 0x74, 0x65, 0x6d, 0x70, 0x2e, 0x54, 0x65, 0x6d,
	0x70, 0x65, 0x72, 0x61, 0x74, 0x75, 0x72, 0x65, 0x52, 0x04, 0x54, 0x65, 0x6d, 0x70, 0x22, 0x89,
	0x01, 0x0a, 0x0b, 0x54, 0x65, 0x6d, 0x70, 0x65, 0x72, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x55, 0x6e, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x55, 0x6e,
	0x69, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x07, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x48, 0x69, 0x67, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x04, 0x48, 0x69, 0x67, 0x68,
	0x12, 0x1a, 0x0a, 0x08, 0x43, 0x72, 0x69, 0x74, 0x69, 0x63, 0x61, 0x6c, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x08, 0x43, 0x72, 0x69, 0x74, 0x69, 0x63, 0x61, 0x6c, 0x12, 0x1c, 0x0a, 0x09,
	0x54, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x09, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x32, 0x40, 0x0a, 0x07, 0x43, 0x70, 0x75, 0x54, 0x65, 0x6d, 0x70, 0x12, 0x35,
	0x0a, 0x11, 0x47, 0x65, 0x74, 0x43, 0x70, 0x75, 0x54, 0x65, 0x6d, 0x70, 0x65, 0x72, 0x61, 0x74,
	0x75, 0x72, 0x65, 0x12, 0x0e, 0x2e, 0x63, 0x70, 0x75, 0x74, 0x65, 0x6d, 0x70, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x1a, 0x0e, 0x2e, 0x63, 0x70, 0x75, 0x74, 0x65, 0x6d, 0x70, 0x2e, 0x55, 0x6e,
	0x69, 0x74, 0x73, 0x22, 0x00, 0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x52, 0x61, 0x6d, 0x61, 0x7a, 0x61, 0x6e, 0x44, 0x65, 0x6d, 0x69, 0x72,
	0x63, 0x69, 0x2f, 0x67, 0x52, 0x50, 0x43, 0x2d, 0x43, 0x70, 0x75, 0x54, 0x65, 0x6d, 0x70, 0x2f,
	0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpc_Cpu_protobuf_cpu_temp_proto_rawDescOnce sync.Once
	file_grpc_Cpu_protobuf_cpu_temp_proto_rawDescData = file_grpc_Cpu_protobuf_cpu_temp_proto_rawDesc
)

func file_grpc_Cpu_protobuf_cpu_temp_proto_rawDescGZIP() []byte {
	file_grpc_Cpu_protobuf_cpu_temp_proto_rawDescOnce.Do(func() {
		file_grpc_Cpu_protobuf_cpu_temp_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_Cpu_protobuf_cpu_temp_proto_rawDescData)
	})
	return file_grpc_Cpu_protobuf_cpu_temp_proto_rawDescData
}

var file_grpc_Cpu_protobuf_cpu_temp_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_grpc_Cpu_protobuf_cpu_temp_proto_goTypes = []interface{}{
	(*Units)(nil),       // 0: cputemp.Units
	(*Temperature)(nil), // 1: cputemp.Temperature
	(*Empty)(nil),       // 2: cputemp.Empty
}
var file_grpc_Cpu_protobuf_cpu_temp_proto_depIdxs = []int32{
	1, // 0: cputemp.Units.Temp:type_name -> cputemp.Temperature
	2, // 1: cputemp.CpuTemp.GetCpuTemperature:input_type -> cputemp.Empty
	0, // 2: cputemp.CpuTemp.GetCpuTemperature:output_type -> cputemp.Units
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_grpc_Cpu_protobuf_cpu_temp_proto_init() }
func file_grpc_Cpu_protobuf_cpu_temp_proto_init() {
	if File_grpc_Cpu_protobuf_cpu_temp_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpc_Cpu_protobuf_cpu_temp_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Units); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_Cpu_protobuf_cpu_temp_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Temperature); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_Cpu_protobuf_cpu_temp_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_Cpu_protobuf_cpu_temp_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_Cpu_protobuf_cpu_temp_proto_goTypes,
		DependencyIndexes: file_grpc_Cpu_protobuf_cpu_temp_proto_depIdxs,
		MessageInfos:      file_grpc_Cpu_protobuf_cpu_temp_proto_msgTypes,
	}.Build()
	File_grpc_Cpu_protobuf_cpu_temp_proto = out.File
	file_grpc_Cpu_protobuf_cpu_temp_proto_rawDesc = nil
	file_grpc_Cpu_protobuf_cpu_temp_proto_goTypes = nil
	file_grpc_Cpu_protobuf_cpu_temp_proto_depIdxs = nil
}
